### ISSUE TITLE
Some punctuations like eiphens (-), back slash (/) got removed while training the flair model

### ISSUE THREAD

**Issue by ammu11** [microsoft/presidio-research#18]
When  I tried to train the flair model,  some punctuations like eiphens (-), back slash (/) and so on  got removed while training the flair model. So could you please help me to overcome the above issue. I am using this code https://github.com/microsoft/presidio-research/blob/master/models/flair_train.py for training the flair model. 

For example when I trained the date entity with this format which is 03-03-2020, when i tested with 03 03 2020, it works and 
it is not working when i tested with  03-03-2020 format.

**Comment by omri374** [comment]
Hi,
I think this might be an issue with flair. I can't think of a process in presidio-research which removes punctuation symbols during training.
