### ISSUE TITLE
bug in EvaluationResult print (precision and recall swapped)

### ISSUE THREAD

**Issue by kevin-yauris** [microsoft/presidio-research#20]
https://github.com/microsoft/presidio-research/blob/50e60b773e54530a52e7e28a4e8c645f42589f9b/presidio_evaluator/data_objects.py#L537

**Comment by omri374** [comment]
Thanks! Are you interested in creating a fix in a PR?

**Comment by kevin-yauris** [comment]
hi @omri374, thanks for your invitation. I already consider it before, but it seems I need to sign some document before I can contribute, and it seems that you already create the PR to fix it. So I think I will skip it for now.

**Comment by omri374** [comment]
fixed on #21
