### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by albusdemens** [microsoft/presidio-research#35]
Hi, I'm starting to dive into Presidio and it's a great tool! I plan to expand the functionalities to detect other types of information; do you think I could use your evaluation code to test how well they work? And do I need to build a specific dataset for that? Thanks

**Comment by omri374** [comment]
Hi @albusdemens, thanks for your issue.

The code in this repo is meant to be used for evaluation of either Presidio or any other model. There's a need for a dataset at least to perform evaluation on existing models/techniques. 

See a high level view of the steps needed here: https://github.com/microsoft/presidio/issues/742#issuecomment-903581824

**Comment by albusdemens** [comment]
Hi @omri374, thank you for your reply and for the information!
