### ISSUE TITLE
PresidioAnalyzerWrapper should call predict with defined language

### ISSUE THREAD

**Issue by ondrasekd** [microsoft/presidio-research#46]
It is possible to costruct a new instance of PresidioAnalyzerWrapper with language other then "en". However, inside of method _predict_,  language "en" is passed as a parameter no matter what language was set during a PresidioAnalyzerWrapper construction.

**Comment by omri374** [comment]
Hi @ondrasekd, would you be interested in creating a PR? I'd be happy to review it.

**Comment by Robbie-Palmer** [comment]
I hadn't seen this issue but noticed this too while making other changes
So currently bundled up in this PR https://github.com/microsoft/presidio-research/pull/50
But can easily be pulled out into a different PR if this is held back due to other changes
