### ISSUE TITLE
Generator template question

### ISSUE THREAD

**Issue by matthewchung74** [microsoft/presidio-research#51]
Is there an example showing how to make a provider that maps to a string for replacement in a template?

For example, if I have a snippet like this

```
class HospitalProvider(BaseProvider):
    def __init__(
        self,
        generator,
    ):
        super().__init__(generator=generator)
        self.hospital_name = "My Test Hospital"

fake = RecordsFaker(records = pd.DataFrame() ,locale="en_US")

sentence_templates = [
    "My name is {{HOSPITAL}}",
    ]

fake.add_provider(HospitalProvider)

```

How do I tell the generator to replace all strings {{HOSPITAL}} with , in this case, My Test Hospital?

**Comment by omri374** [comment]
Hi, will this help? https://faker.readthedocs.io/en/master/#how-to-create-a-dynamic-provider

**Comment by matthewchung74** [comment]
Yes it does. Thanks!
