### ISSUE TITLE
Reference to non existing file 'presidio_evaluator/data_generator/raw_data/organizations.csv'

### ISSUE THREAD

**Issue by melmatlis** [microsoft/presidio-research#56]
Executing `python setup.py install` raises the following error:
`error: can't copy 'presidio_evaluator/data_generator/raw_data/organizations.csv': doesn't exist or not a regular file`
Looking at the directory it seems the file was renamed to "presidio_evaluator/data_generator/raw_data/companies_and_organizations.csv"

**Comment by omri374** [comment]
Good catch. The file changed on PR #55. Would you mind creating a small pr renaming from `organizations.csv` to `companies_and_organizations.csv`?
