### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by Robbie-Palmer** [microsoft/presidio-research#66]
[Presidio](https://github.com/microsoft/presidio) works with Python v3.11 but Presidio Research does not install

Installation fails because this package requires `sklearn_crfsuite` which requires `python-crfsuite` which [throws an error on install related to its C bindings](https://github.com/scrapinghub/python-crfsuite/issues/150)

This should be [in the process of being fixed](https://github.com/scrapinghub/python-crfsuite/pull/151)
But two related improvements could be made in this repo
- Add Python 3.11 as a tested version in `ci.yml`
- Utilise `extras_require` in `setup.py` for optional dependencies
    - So, bugs like this in downstream dependencies only affect people who want those dependencies. E.g. those using spacy vs stanza vs crf vs flair vs azure text analytics models only need to install a subset of the dependencies, and their install will succeed even if there are bugs related to the other model families

**Comment by omri374** [comment]
Hi, having 3rd party modeling packages as extras is a great idea. We'll look into this.

**Comment by omri374** [comment]
Fixed in 0.1.3
