### ISSUE TITLE
Using Flair Embeddings?

### ISSUE THREAD

**Issue by kirkins** [microsoft/presidio-research#7]
Thanks for your work on this project, trying to reproduce locally and possibly expand on it for a graduate project.

We've been able to run all the Notebooks for evaluating models except for `flair`. We run into some issues with embeddings being required in `Evaluate flair models.ipynb`.

```
flair_bert_embeddings = '../../models/presidio-ner/flair-bert-embeddings.pt'
glove_flair_embeddings = '../../models/presidio-ner/flair-embeddings.pt'
```

I was thinking we might be able to import them directly from `flair` with something like:

```
from flair.embeddings import WordEmbeddings, BertEmbeddings

flair_bert_embeddings = BertEmbeddings()
glove_flair_embeddings = WordEmbeddings('glove')
```
But this also resulted in an error.

Do you know where we can download these embedding files?

**Comment by omri374** [comment]
Hi, 
The `flair-bert-embeddings.pt` and `flair-embeddings.pt` files are the output of training a model using Flair. See https://github.com/microsoft/presidio-research/blob/master/models/flair_train.py for how we trained our Flair models.
You could also use pretrained Flair models, like 'ner', 'ner-fast' and 'ner-ontonotes-fast'. These could be loaded the same way: 

```python
from presidio_evaluator.flair_evaluator import FlairEvaluator

flair_evaluator = FlairEvaluator(model_path=model)
evaluation_results = flair_evaluator.evaluate_all(DATASET)
scores = flair_evaluator.calculate_score(evaluation_results)
```

**Comment by kirkins** [comment]
Thanks, running `flair_train.py` now. It seems this will generate the files needed.
