### ISSUE TITLE
Why translate tags in CRF model in predict method?

### ISSUE THREAD

**Issue by ebotiab** [microsoft/presidio-research#80]
The translation of tags procedure in the predict method of the CRF model is repeated, as it can be noted in the lines:

```
sample.translate_input_sample_tags()

conll = sample.to_conll(translate_tags=True)
```
Also, it is not consistent to translate labels, since all other models do not translate labels in their prediction method, so why in the CRF model does?

**Comment by omri374** [comment]
The intention is to translate tags to one unified mapping, in order to compare different models which might output different label names. If it is not consisted, it could be a bug.

**Comment by ebotiab** [comment]
I would say it is actually a bug, since it is not consistent and in addition the process of the translation is repeated, leading to a translation of the translated tags which gives incorrect results. A pull request could be opened fixing it by simpy removing that lines of code, so the model crf predict method expects the translated tags as inputs.

**Comment by omri374** [comment]
Thanks. If you're interested in creating one, I'd be happy to review it.

**Comment by ebotiab** [comment]
Thanks @omri374 !
