### ISSUE TITLE
Default installation fails pytest

### ISSUE THREAD

**Issue by seanlindo** [microsoft/presidio-research#82]
Several tests fail with the following error:

`Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.`

This is a clean virtual environment based on Python 3.9 following the "From Source" instructions. 113 tests pass (5 are skipped) after running `python -m spacy download en_core_web_sm`.

I will send a PR to clarify the documentation.

**Comment by omri374** [comment]
Thanks! spaCy models are sometimes challenging to install automatically. A clarification to the documentation would be great.

**Comment by omri374** [comment]
Closing for now, please reopen if the documentation is still not clear enough
