### ISSUE TITLE
Fine-tuning flair model

### ISSUE THREAD

**Issue by filiallags0i** [microsoft/presidio-research#99]
Can you provide more details on the fine tuning approach here that is discussed in the README?  It says that Flair models can be trained with trainer.train(corpus), but no such method exists.  Also, how would you take an existing flair model and fine tune it with FlairTrainer?  An example would be great!  Thanks!

**Comment by omri374** [comment]
Hi, it could be that the codebase for supporting flair is not up to date, we'll look into this.
In the mean time, I would suggest to look at the flair docs for training: https://flairnlp.github.io/docs/tutorial-training/how-to-train-sequence-tagger

From looking into the code, there's a `ModelTrainer` class which as a `train` method: https://github.com/flairNLP/flair/blob/223f346c5a669e628e81a6b470bb44b6c6b37286/flair/trainers/trainer.py#L126

**Comment by omri374** [comment]
The flair trainer was removed from this codebase. Refer to Flair's documentation on training Flair models.
